"""add equipment.deleted_at

Revision ID: 8441fd923515
Revises: d847c8775fdc
Create Date: 2026-06-03 17:05:24.498191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8441fd923515'
down_revision: Union[str, None] = 'd847c8775fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'deleted_at')
    # ### end Alembic commands ###
